"""
blog/urls.py  —  DRF Router wires up all ViewSets automatically.

Route table generated by the router
─────────────────────────────────────────────────────────────────
GET    /api/v1/posts/                 PostViewSet.list
POST   /api/v1/posts/                 PostViewSet.create
GET    /api/v1/posts/{id}/            PostViewSet.retrieve
PUT    /api/v1/posts/{id}/            PostViewSet.update
PATCH  /api/v1/posts/{id}/            PostViewSet.partial_update
DELETE /api/v1/posts/{id}/            PostViewSet.destroy
POST   /api/v1/posts/{id}/publish/    PostViewSet.publish    (custom)
POST   /api/v1/posts/{id}/archive/    PostViewSet.archive    (custom)
GET    /api/v1/posts/featured/        PostViewSet.featured   (custom)
GET    /api/v1/posts/my_posts/        PostViewSet.my_posts   (custom)

GET    /api/v1/posts/{post_pk}/comments/        CommentViewSet.list
POST   /api/v1/posts/{post_pk}/comments/        CommentViewSet.create
GET    /api/v1/posts/{post_pk}/comments/{id}/   CommentViewSet.retrieve
PATCH  /api/v1/posts/{post_pk}/comments/{id}/   CommentViewSet.partial_update
DELETE /api/v1/posts/{post_pk}/comments/{id}/   CommentViewSet.destroy

GET    /api/v1/categories/            CategoryViewSet.list
POST   /api/v1/categories/            CategoryViewSet.create
...

GET    /api/v1/tags/                  TagViewSet.list
POST   /api/v1/tags/                  TagViewSet.create
...

POST   /api/v1/auth/register/         RegisterView
"""
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework_nested import routers as nested_routers

from .views import (
    CategoryViewSet, TagViewSet,
    PostViewSet, CommentViewSet,
    RegisterView,
)

router = DefaultRouter()
router.register(r'posts',      PostViewSet,     basename='post')
router.register(r'categories', CategoryViewSet, basename='category')
router.register(r'tags',       TagViewSet,      basename='tag')
router.register(r'comments',   CommentViewSet,  basename='comment')   # admin view


try:
    posts_router = nested_routers.NestedDefaultRouter(router, r'posts', lookup='post')
    posts_router.register(r'comments', CommentViewSet, basename='post-comments')
    nested_urls = posts_router.urls
except Exception:
  
    nested_urls = []

urlpatterns = [
    path('', include(router.urls)),
    path('', include(nested_urls)),


    path('auth/register/', RegisterView.as_view(), name='register'),
]
